"""Compatibility constants delegated to external :mod:`chatstyle`."""

from chatstyle import (
    BACK_VALUE,
    CHECKBOX_SELECTED_INDICATOR,
    CHECKBOX_UNSELECTED_INDICATOR,
    FORCE_INTERACTIVE_NO_TTY_MESSAGE,
    INTERACTIVE_OPTION_HELP,
    MISSING_REQUIRED_NO_TTY_MESSAGE,
)


__all__ = [
    "BACK_VALUE",
    "CHECKBOX_SELECTED_INDICATOR",
    "CHECKBOX_UNSELECTED_INDICATOR",
    "FORCE_INTERACTIVE_NO_TTY_MESSAGE",
    "INTERACTIVE_OPTION_HELP",
    "MISSING_REQUIRED_NO_TTY_MESSAGE",
]
